export const typeColors: { [key: string]: string } = {
    bug: 'bg-green-500 text-white',
    dragon: 'bg-orange-500 text-white',
    fairy: 'bg-pink-300 text-black',
    fire: 'bg-orange-600 text-white',
    ghost: 'bg-purple-500 text-white',
    ground: 'bg-yellow-500 text-black',
    normal: 'bg-gray-300 text-black',
    psychic: 'bg-pink-600 text-white',
    steel: 'bg-gray-500 text-white',
    dark: 'bg-gray-700 text-white',
    electric: 'bg-yellow-300 text-black',
    fighting: 'bg-red-600 text-white',
    flying: 'bg-blue-300 text-black',
    grass: 'bg-green-300 text-black',
    ice: 'bg-blue-200 text-black',
    poison: 'bg-purple-300 text-black',
    rock: 'bg-yellow-600 text-black',
    water: 'bg-blue-500 text-white',
}